-- wiki.lua
-- 1. Remove indexref spans (generated by Word index add-in)
-- 2. Promote bold-only paragraphs to h2
-- 3. Promote plain paragraphs immediately before a bullet list to h4
-- 4. Strip auto-generated ids from headings
-- 5. Fix image paths to be relative to the output file

function Span(el)
  if el.classes:includes("indexref") then return {} end
end

function Image(el)
  -- Strip the output file's directory prefix from image src so paths are
  -- relative to the HTML file rather than the pandoc working directory.
  local out = PANDOC_STATE.output_file
  if out then
    local dir = out:match("^(.*[/\\])") or ""
    if dir ~= "" and el.src:sub(1, #dir) == dir then
      el.src = el.src:sub(#dir + 1)
    end
  end
  return el
end

function Header(el)
  el.identifier = ""
  return el
end

function Pandoc(doc)
  local blocks = {}
  local n = #doc.blocks
  for i = 1, n do
    local b = doc.blocks[i]
    local next_b = doc.blocks[i + 1]

    if b.t == "Para" then
      -- Bold-only paragraph → h2
      if #b.content == 1 and b.content[1].t == "Strong" then
        table.insert(blocks, pandoc.Header(2, b.content[1].content))

      -- Plain short paragraph before a bullet list → h4
      elseif next_b and next_b.t == "BulletList"
          and #b.content > 0
          and pandoc.utils.stringify(b) ~= "" then
        table.insert(blocks, pandoc.Header(4, b.content))

      else
        table.insert(blocks, b)
      end
    else
      table.insert(blocks, b)
    end
  end
  return pandoc.Pandoc(blocks, doc.meta)
end
